export enum TipoActaGradoEnum {
  // TITULACIÓN
  T_EGCC = "T-EXAMEN-GRADO-CARACTER-COMPLEXIVO",
  T_PIAA = "T-PROYECTO-INVESTIGACIÓN-ARTÍCULO-ACADÉMICO",

  // INTEGRACIÓN CURRICULAR
  IC_EGCC = "IC-EXAMEN-GRADO-CARACTER-COMPLEXIVO",
  IC_PIAA = "IC-PROYECTO-INVESTIGACIÓN-ARTÍCULO-ACADÉMICO",
}

export enum EstadoActaEnum {
  APRO = "APRO",
  REPR = "REPR",
  NO_RESENTACION = "NO_RESENTACION",
}
