export enum ModuleEnum {
  FACU = "FACU",
  SUDE = "SUDE",
  TITU = "TITU",
  CURR = "CURR",
  COMM = "COMM",
  //TITULACION
  SIST = "SIST",
  INPA = "INPA",
  ELEC = "ELEC",
  //TITULACION
  //INTEGRACION CURRICULAR
  SOFT = "SOFT",
  TECI = "TECI",
  TELE = "TELE",
  INDS = "INDS",
  //INTEGRACION CURRICULAR 
}
