export enum PlantillasGlobales {
  PLA_ACT_FACU = "PLA_ACT::FACU",
  PLA_ACT_SEP_FACU = "PLA_ACT_SEP::FACU",
  PLA_ACT_SUDE = "PLA_ACT::SUDE",
  PLA_ACT_SEP_SUDE = "PLA_ACT_SEP::SUDE",
  PLA_ACT_TITU = "PLA_ACT::TITU",
  PLA_ACT_SEP_TITU = "PLA_ACT_SEP::TITU",
  PLA_ACT_CURR = "PLA_ACT::CURR",
  PLA_ACT_SEP_CURR = "PLA_ACT_SEP::CURR",
  PLAN_SUBIR_ESTUDIANTES = "PLAN_SUBIR_ESTUDIANTES",

  //TITULACION
  PLA_ACT_SIST = "PLA_ACT::SIST",
  PLA_ACT_SEP_SIST = "PLA_ACT_SEP::SIST",
  PLA_ACT_INPA = "PLA_ACT::INPA",
  PLA_ACT_SEP_INPA = "PLA_ACT_SEP::INPA",
  PLA_ACT_ELEC = "PLA_ACT::ELEC",
  PLA_ACT_SEP_ELEC = "PLA_ACT_SEP::ELEC",
  //TITULACION
  //INTEGRACION CURRICULAR
  PLA_ACT_SOFT = "PLA_ACT::SOFT",
  PLA_ACT_SEP_SOFT = "PLA_ACT_SEP::SOFT",
  PLA_ACT_TECI = "PLA_ACT::TECI",
  PLA_ACT_SEP_TECI = "PLA_ACT_SEP::TECI",
  PLA_ACT_TELE = "PLA_ACT::TELE",
  PLA_ACT_SEP_TELE = "PLA_ACT_SEP::TELE",
  PLA_ACT_INDS = "PLA_ACT::INDS",
  PLA_ACT_SEP_INDS = "PLA_ACT_SEP::INDS",
  //INTEGRACION CURRICULAR
}
