export enum PlantillasGlobales {
  PLA_ACT_FACU = "PLA_ACT::FACU",
  PLA_ACT_SEP_FACU = "PLA_ACT_SEP::FACU",
  PLA_ACT_SUDE = "PLA_ACT::SUDE",
  PLA_ACT_SEP_SUDE = "PLA_ACT_SEP::SUDE",
  PLA_ACT_TITU = "PLA_ACT::TITU",
  PLA_ACT_SEP_TITU = "PLA_ACT_SEP::TITU",
  PLA_ACT_CURR = "PLA_ACT::CURR",
  PLA_ACT_SEP_CURR = "PLA_ACT_SEP::CURR",
  PLAN_SUBIR_ESTUDIANTES = "PLAN_SUBIR_ESTUDIANTES",
}
